"""add flow_prompt to seo_packages

Revision ID: 412cf774fe2a
Revises: 6032f9d12232
Create Date: 2026-10-01 21:55:17.487458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412cf774fe2a'
down_revision = '6032f9d12232'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seo_packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flow_prompt', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seo_packages', schema=None) as batch_op:
        batch_op.drop_column('flow_prompt')

    # ### end Alembic commands ###
