"""initial schema

Revision ID: 6032f9d12232
Revises: 
Create Date: 2026-10-01 19:59:11.659237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6032f9d12232'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_language', sa.String(length=50), nullable=False),
    sa.Column('default_duration', sa.String(length=50), nullable=False),
    sa.Column('visual_style', sa.String(length=100), nullable=False),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=True)

    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('story_text', sa.Text(), nullable=True),
    sa.Column('ending', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('mood', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'PUBLISHED', name='storystatus'), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('signature_json', sa.Text(), nullable=True),
    sa.Column('characters_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stories_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stories_id'), ['id'], unique=False)

    op.create_table('generation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('generation_attempt', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('duplicate_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_logs_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_logs_id'), ['id'], unique=False)

    op.create_table('scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('visual_description', sa.Text(), nullable=True),
    sa.Column('dialogue_json', sa.Text(), nullable=True),
    sa.Column('camera', sa.String(length=200), nullable=True),
    sa.Column('music_sfx', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenes_story_id'), ['story_id'], unique=False)

    op.create_table('seo_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('youtube_title', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('thumbnail_text', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seo_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seo_packages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seo_packages_story_id'), ['story_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seo_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seo_packages_story_id'))
        batch_op.drop_index(batch_op.f('ix_seo_packages_id'))

    op.drop_table('seo_packages')
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenes_story_id'))
        batch_op.drop_index(batch_op.f('ix_scenes_id'))

    op.drop_table('scenes')
    with op.batch_alter_table('generation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_logs_id'))
        batch_op.drop_index(batch_op.f('ix_generation_logs_category_id'))

    op.drop_table('generation_logs')
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stories_id'))
        batch_op.drop_index(batch_op.f('ix_stories_category_id'))

    op.drop_table('stories')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))
        batch_op.drop_index(batch_op.f('ix_categories_id'))

    op.drop_table('categories')
    # ### end Alembic commands ###
