"""add ai_provider and ai_model to stories

Revision ID: e0fcc4e2db95
Revises: 412cf774fe2a
Create Date: 2026-10-01 23:38:17.027581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0fcc4e2db95'
down_revision = '412cf774fe2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ai_model', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('ai_model')
        batch_op.drop_column('ai_provider')

    # ### end Alembic commands ###
